### ISSUE TITLE
betweenness centrality build failure on mario

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#104]
It's noted that this error is in nvcc 7.0 and fixed in 7.5.

```
[ 21%] Building NVCC (Device) object tests/bc/CMakeFiles/betweenness_centrality.dir/betweenness_centrality_generated_test_bc.cu.o
/home/jowens/working/gunrock/externals/moderngpu/include/kernels/segreducecsr.cuh:394:8: warning: âauto_ptrâ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  CudaContext& context) {
        ^
/home/jowens/working/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh:177:29: warning: âauto_ptrâ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  std::auto_ptr<ReduceByKeyPreprocessData>* ppData, CudaContext& context) {
                             ^
/home/jowens/working/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh: In function âvoid mgpu::ReduceByKeyPreprocess(int, KeysIt, KeyType*, Comp, int*, int*, std::auto_ptr<mgpu::SegReducePreprocessData>*, mgpu::CudaContext&)â:
/home/jowens/working/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh:186:45: warning: âauto_ptrâ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
   data(new ReduceByKeyPreprocessData);
                                             ^
/home/jowens/working/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh: In function âvoid mgpu::ReduceByKey(KeysIt, InputIt, int, ValType, Op, Comp, KeyType*, DestIt, int*, int*, mgpu::CudaContext&)â:
/home/jowens/working/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh:248:41: warning: âauto_ptrâ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  std::auto_ptr<ReduceByKeyPreprocessData> data;
                                         ^
/home/jowens/working/gunrock/externals/moderngpu/include/kernels/spmvcsr.cuh: At global scope:
/home/jowens/working/gunrock/externals/moderngpu/include/kernels/spmvcsr.cuh:423:8: warning: âauto_ptrâ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  CudaContext& context) {
        ^
/home/jowens/working/gunrock/externals/moderngpu/include/kernels/spmvcsr.cuh:433:8: warning: âauto_ptrâ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  CudaContext& context) {
        ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:75: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                           ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:97: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                 ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:121: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                         ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:145: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                 ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:169: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                         ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:193: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                 ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:217: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                         ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:241: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                 ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:265: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                                         ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:289: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                                                                 ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:313: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                                                                                         ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:338: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                                                                                                                  ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:363: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                                                                                                                                           ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:388: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                                                                                                                                                                    ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:413: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                                                                                                                                                                                             ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:438: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^
/usr/local/include/boost/utility/detail/result_of_iterate.hpp:148:463: error: invalid use of qualified-name âstd::allocator_traits<_Alloc>::propagate_on_container_swapâ
   ) type;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^
CMake Error at betweenness_centrality_generated_test_bc.cu.o.cmake:266 (message):
  Error generating file
  /home/jowens/working/gunrock-build/tests/bc/CMakeFiles/betweenness_centrality.dir//./betweenness_centrality_generated_test_bc.cu.o
```

**Comment by yzhwang** [comment]
I think sssp and mst on dev branch with CUDA 7.0 also have such issue (same error). I think it is related to the adding of c++11 flag. Maybe it causes some conflict with boost when using CUDA 7.0.

**Comment by jowens** [comment]
yes, the internet seems to indicate that it's a nvcc 7.0 error with C++11 (boost is the symptom).

**Comment by sgpyc** [comment]
Anyway to get the actual make commend? The problem is introduced by commit 390f5b1 (added --std=c++11 in CMakeLists.txt ), but may not be an CUDA 7.0 vs. 7.5 issue : my default nvcc is 7.5, but it still fails to make the build directory (it passes tests/bc make though).

**Comment by jowens** [comment]
http://stackoverflow.com/questions/31940457/make-nvcc-output-traces-on-compile-error

**Comment by jowens** [comment]
https://stackoverflow.com/questions/31969644/compilation-error-with-nvcc-and-c11-need-minimal-failing-example

**Comment by jowens** [comment]
https://github.com/psteinb/libmultiviewnative/issues/1#issuecomment-111060769

**Comment by sgpyc** [comment]
Built make past on top of dev on luigi, looks like we have no so updated software on mario.

Luigi:
  Ubuntu 14.04.1
  gcc 4.8.5
  nvcc 7.5.17
  boost 1.58.0

Mario:
  ubuntu 14.04
  gcc 4.8.4
  nvcc 7.5.6
  boost 1.58.0

**Comment by sgpyc** [comment]
1. when software on mario updated to the same as luigi, problem still existed;
2. CUDA_NVCC_EXECUTABLE was been set to /usr/local/cuda-7.0/bin/nvcc, even after running cmake <gunrock_dir> ;
3. CUDA_NVCC_EXECUTABLE is cached in <build_dir>/CMakeCache.txt, that file seems have not been updated frequently;
4. delete <build_dir>/CMakeCache.txt, run cmake <gunrock_dir> to generate a new CMakeCache.txt -> problem solved.

Suggestion: don't use CMakeCache.txt. if I run cmake <gunrock_dir>, that means I want to update all the Makefiles with new environmental settings, should check everything in this case

**Comment by yzhwang** [comment]
Thank you @sgpyc! Is this a runtime mismatch issue or does this mean our latest version won't work for CUDA version <= 7.0? Just want to make sure.

**Comment by sgpyc** [comment]
I think nvcc (<= 7.0) has known issue (pointed by @jowens 's links) working with boost when c++11 is enabled. nvcc (>=7.5 RC) solved the issue.

**Comment by jowens** [comment]
If we want to require 7.5, let's make that an explicit decision (and we need to update the docs accordingly). Since we've indicated we will move to C++11, that's a sensible decision, and I'm fine with it.

**Comment by jowens** [comment]
Closing this because we now require 7.5.
