### ISSUE TITLE
 Internal Compiler Error (codegen) when trying to build gunrock

### ISSUE THREAD

**Issue by wolfram77** [gunrock/gunrock#1059]
I am trying the build gunrock from source with cmake, but get the following error when building.

```bash
/home/graphwork/.local/include/nlohmann/ordered_map.hpp(29): error: Internal Compiler Error (codegen): "internal error during structure layout!"

make[2]: *** [/home/graphwork/Documents/Test-gunrock/gunrock--gunrock/externals/nvbench-build/nvbench/CMakeFiles/nvbench.dir/build.make:465: /home/graphwork/Documents/Test-gunrock/gunrock--gunrock/externals/nvbench-build/nvbench/CMakeFiles/nvbench.dir/json_printer.cu.o] Error 2
make[2]: *** Waiting for unfinished jobs....

...

make[1]: *** [CMakeFiles/Makefile2:1379: /home/graphwork/Documents/Test-gunrock/gunrock--gunrock/externals/nvbench-build/nvbench/CMakeFiles/nvbench.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

...

make: *** [Makefile:146: all] Error 2
```

It seems this is related to nvbench or nlohmann/json.

I was able to build gunrock earlier with the commit id ee267a8f13c51cdf0753286fbe49b2dfcf28c6fb (Merge pull request gunrock#1049 from marjerie/main).

Details from cmake are below.

```bash
-- Defaulting to Release build type
-- The CXX compiler identification is GNU 9.4.0
-- The C compiler identification is GNU 9.4.0
-- The CUDA compiler identification is NVIDIA 11.4.152

...

-- Cloning External Project: Thrust
-- Cloning External Project: ModernGPU
-- Cloning External Project: CXXOPTS
-- Cloning External Project: NLohmannJson
-- Cloning External Project: CMake Modules

...

-- Found Threads: TRUE

...

-- Cloning External Project: GoogleTests
CMake Deprecation Warning at externals/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

...

-- Found Python: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter
-- Cloning External Project: NVBench
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.4.152")
-- Performing Test NVBench_CXX_FLAG__Wall
-- Performing Test NVBench_CXX_FLAG__Wall - Success

...

-- Found Git: /usr/bin/git (found version "2.25.1")
-- CPM: Using local package fmt@10.1.1
-- CPM: Using local package nlohmann_json@3.11.2
-- NVBench CUDA architectures: 52

...
```

I uploaded the full build log [here](https://gist.github.com/wolfram77/168b8ddad88d89f6cc1657cd0e07193c).

**Comment by jowens** [comment]
There's a note [here](https://github.com/kokkos/mdspan/issues/97) that a similar bug was fixed in CUDA 11.6. Could you consider upgrading your CUDA install? Looks like you're at 11.4.

**Comment by neoblizz** [comment]
Can you also try a different Architecture `-DCMAKE_CUDA_ARCHITECTURES=70`?

**Comment by wolfram77** [comment]
I tried with `cmake -DCMAKE_CUDA_ARCHITECTURES=70 ..` and getting the same error as earlier.

```bash
/home/graphwork/.local/include/nlohmann/ordered_map.hpp(29): error: Internal Compiler Error (codegen): "internal error during structure layout!"
```

I will try upgrading CUDA.

**Comment by wolfram77** [comment]
gunrock build worked on CUDA 12.3. Thanks.
