### ISSUE TITLE
problems in  compling

### ISSUE THREAD

**Issue by jiangjiaqi6** [gunrock/gunrock#681]
**Summary:**
I can't compile the code of the v0.5.1

**Reproducibility:**
Always 

**To Reproduce:**
when i input the command of make -j8, errors occur.
[  3%] Linking CXX executable ../../bin/bc
[  7%] Linking CXX executable ../../bin/cc
[ 11%] Linking CXX executable ../../bin/astar
[ 15%] Linking CXX executable ../../bin/hits
[ 19%] Built target gunrock
[ 23%] Linking CXX executable ../../bin/bfs
[ 30%] Linking CXX executable ../../bin/sssp
[ 30%] Linking CXX executable ../../bin/pr
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
[ 34%] Linking CXX executable ../../bin/salsa
examples/cc/CMakeFiles/cc.dir/build.make:76: recipe for target 'bin/cc' failed
make[2]: *** [bin/cc] Error 1
examples/bc/CMakeFiles/bc.dir/build.make:76: recipe for target 'bin/bc' failed
make[2]: *** [bin/bc] Error 1
CMakeFiles/Makefile2:611: recipe for target 'examples/cc/CMakeFiles/cc.dir/all' failed
make[1]: *** [examples/cc/CMakeFiles/cc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:501: recipe for target 'examples/bc/CMakeFiles/bc.dir/all' failed
make[1]: *** [examples/bc/CMakeFiles/bc.dir/all] Error 2
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
examples/hits/CMakeFiles/hits.dir/build.make:76: recipe for target 'bin/hits' failed
make[2]: *** [bin/hits] Error 1
CMakeFiles/Makefile2:776: recipe for target 'examples/hits/CMakeFiles/hits.dir/all' failed
make[1]: *** [examples/hits/CMakeFiles/hits.dir/all] Error 2
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
examples/bfs/CMakeFiles/bfs.dir/build.make:76: recipe for target 'bin/bfs' failed
make[2]: *** [bin/bfs] Error 1
CMakeFiles/Makefile2:556: recipe for target 'examples/bfs/CMakeFiles/bfs.dir/all' failed
make[1]: *** [examples/bfs/CMakeFiles/bfs.dir/all] Error 2
examples/sssp/CMakeFiles/sssp.dir/build.make:76: recipe for target 'bin/sssp' failed
make[2]: *** [bin/sssp] Error 1
examples/astar/CMakeFiles/astar.dir/build.make:76: recipe for target 'bin/astar' failed
make[2]: *** [bin/astar] Error 1
CMakeFiles/Makefile2:721: recipe for target 'examples/sssp/CMakeFiles/sssp.dir/all' failed
make[1]: *** [examples/sssp/CMakeFiles/sssp.dir/all] Error 2
CMakeFiles/Makefile2:446: recipe for target 'examples/astar/CMakeFiles/astar.dir/all' failed
make[1]: *** [examples/astar/CMakeFiles/astar.dir/all] Error 2
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
examples/pr/CMakeFiles/pr.dir/build.make:76: recipe for target 'bin/pr' failed
make[2]: *** [bin/pr] Error 1
CMakeFiles/Makefile2:666: recipe for target 'examples/pr/CMakeFiles/pr.dir/all' failed
make[1]: *** [examples/pr/CMakeFiles/pr.dir/all] Error 2
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
examples/salsa/CMakeFiles/salsa.dir/build.make:76: recipe for target 'bin/salsa' failed
make[2]: *** [bin/salsa] Error 1
CMakeFiles/Makefile2:831: recipe for target 'examples/salsa/CMakeFiles/salsa.dir/all' failed
make[1]: *** [examples/salsa/CMakeFiles/salsa.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Expected Behavior:**
I just want to compile successfully.

**System Configuration:**

GPU: GTX 2080
CPU: Intel(R) Xeon(R) CPU E3-1280 v5 @ 3.70GHz
OS: Ubuntu 18.04.1 LTS
Cuda compilation tools, release 10.1
NVIDIA-SMI 430.50
Driver Version: 430.50
CUDA Version: 10.1
gcc  5.5

**Comment by jowens** [comment]
Seems likely to me you're not using a supported host compiler (gcc). For Ubuntu 18 and CUDA 10.2, you need gcc 7.3.

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by jiangjiaqi6** [comment]
It doesn't work if I upgrade GCC to 7. Do I have to upgrade to CUDA 10.2. My previous version was due to bugs in running multiple GPUs, and then sent an issue. The person in charge of gunrock library told me to use v0.5.1. Could you recommend a CUDA 10.1 version for me and run BFS on multiple GPUs.I thank you very much.

**Comment by jowens** [comment]
You need to make sure that your gcc version is the precise version that the CUDA version you are using requires. This is not a Gunrock thing, this is a CUDA thing. I believe multi-GPU BFS will work with CUDA 10.1, but you have to use the exact version that NVIDIA requires (in this case, 7.4 https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-linux/index.html).
