### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by zhz44** [gunrock/gunrock#259]
Hi, 

I am trying to compile Gunrock on Fedora 23 with CUDA 7.5, the gcc version is 5.3.1, I am using the newest version of Gunrock, however, the cmake .. does not report any issue. However, when I am running make, I got the following error: 

make
[  1%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o
/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_000004ed_00000000-10_mgpucontext.compute_35.cpp1.ii".
CMake Error at gunrock_generated_mgpucontext.cu.o.cmake:266 (message):
  Error generating file
  /home/zhz44/Project/gunrock/build/gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/./gunrock_generated_mgpucontext.cu.o

gunrock/CMakeFiles/gunrock.dir/build.make:119: recipe for target 'gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o' failed
make[2]: *** [gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'gunrock/CMakeFiles/gunrock.dir/all' failed
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhz44** [comment]
Hi, 

No worries, I think I know whats happened, the problem is that the GCC 5 does not work with CUDA 7.5.

**Comment by jowens** [comment]
Yup, that's right. 

http://developer.download.nvidia.com/compute/cuda/7.5/Prod/docs/sidebar/CUDA_Installation_Guide_Linux.pdf
